name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: DX
        run: |
          go run cmd/adventlang.go tests/__run_tests.adv

      - name: Wasm
        run: |
          GOOS=js GOARCH=wasm go build -o docs/adventlang.wasm web/run.go
